<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFqjjGjP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFqjjGjP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFqjjGjP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFqjjGjP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFqjjGjP\App_KernelDevDebugContainer([
    'container.build_hash' => 'FqjjGjP',
    'container.build_id' => 'd8c6fde2',
    'container.build_time' => 1719927416,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFqjjGjP');
